import { Team, Fixture, LeagueCode, LeagueInfo, AIParlay } from '@/types';

export const LEAGUES_DATA: Record<LeagueCode, LeagueInfo> = {
  PL: {
    code: 'PL',
    oddsApiKey: 'soccer_epl',
    name: 'Premier League',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    emblem_url: 'https://crests.football-data.org/PL.png',
    avgHomeGoals: 1.62,
    avgAwayGoals: 1.34,
  },
  PD: {
    code: 'PD',
    oddsApiKey: 'soccer_spain_la_liga',
    name: 'La Liga',
    country: 'Spain',
    flag: '🇪🇸',
    emblem_url: 'https://crests.football-data.org/PD.png',
    avgHomeGoals: 1.48,
    avgAwayGoals: 1.15,
  },
  SA: {
    code: 'SA',
    oddsApiKey: 'soccer_italy_serie_a',
    name: 'Serie A',
    country: 'Italy',
    flag: '🇮🇹',
    emblem_url: 'https://crests.football-data.org/SA.png',
    avgHomeGoals: 1.42,
    avgAwayGoals: 1.18,
  },
  BL1: {
    code: 'BL1',
    oddsApiKey: 'soccer_germany_bundesliga',
    name: 'Bundesliga',
    country: 'Germany',
    flag: '🇩🇪',
    emblem_url: 'https://crests.football-data.org/BL1.png',
    avgHomeGoals: 1.74,
    avgAwayGoals: 1.41,
  },
  FL1: {
    code: 'FL1',
    oddsApiKey: 'soccer_france_ligue_one',
    name: 'Ligue 1',
    country: 'France',
    flag: '🇫🇷',
    emblem_url: 'https://crests.football-data.org/FL1.png',
    avgHomeGoals: 1.45,
    avgAwayGoals: 1.20,
  },
};

export const MOCK_TEAMS: Record<string, Team> = {
  // Premier League
  'arsenal': {
    id: 'arsenal',
    league: 'PL',
    name: 'Arsenal',
    aliases: ['Arsenal FC'],
    attack_rating: 1.38,
    defense_rating: 0.65,
    form: 'WWWDW',
    crest_url: 'https://crests.football-data.org/57.png',
  },
  'manchester-city': {
    id: 'manchester-city',
    league: 'PL',
    name: 'Manchester City',
    aliases: ['Man City', 'Manchester City FC'],
    attack_rating: 1.45,
    defense_rating: 0.72,
    form: 'WDWWW',
    crest_url: 'https://crests.football-data.org/65.png',
  },
  'liverpool': {
    id: 'liverpool',
    league: 'PL',
    name: 'Liverpool',
    aliases: ['Liverpool FC'],
    attack_rating: 1.40,
    defense_rating: 0.70,
    form: 'WWWLW',
    crest_url: 'https://crests.football-data.org/64.png',
  },
  'chelsea': {
    id: 'chelsea',
    league: 'PL',
    name: 'Chelsea',
    aliases: ['Chelsea FC'],
    attack_rating: 1.18,
    defense_rating: 0.92,
    form: 'WDLWW',
    crest_url: 'https://crests.football-data.org/61.png',
  },
  'tottenham': {
    id: 'tottenham',
    league: 'PL',
    name: 'Tottenham Hotspur',
    aliases: ['Spurs', 'Tottenham'],
    attack_rating: 1.22,
    defense_rating: 1.05,
    form: 'LWWDL',
    crest_url: 'https://crests.football-data.org/73.png',
  },
  'aston-villa': {
    id: 'aston-villa',
    league: 'PL',
    name: 'Aston Villa',
    aliases: ['Villa', 'Aston Villa FC'],
    attack_rating: 1.20,
    defense_rating: 0.88,
    form: 'WWLDW',
    crest_url: 'https://crests.football-data.org/58.png',
  },
  'newcastle': {
    id: 'newcastle',
    league: 'PL',
    name: 'Newcastle United',
    aliases: ['Newcastle'],
    attack_rating: 1.15,
    defense_rating: 0.94,
    form: 'DWWLD',
    crest_url: 'https://crests.football-data.org/67.png',
  },
  'wolves': {
    id: 'wolves',
    league: 'PL',
    name: 'Wolverhampton Wanderers',
    aliases: ['Wolves'],
    attack_rating: 0.88,
    defense_rating: 1.25,
    form: 'LDLLD',
    crest_url: 'https://crests.football-data.org/76.png',
  },

  // La Liga
  'real-madrid': {
    id: 'real-madrid',
    league: 'PD',
    name: 'Real Madrid',
    aliases: ['Real Madrid CF'],
    attack_rating: 1.46,
    defense_rating: 0.62,
    form: 'WWWDW',
    crest_url: 'https://crests.football-data.org/86.png',
  },
  'barcelona': {
    id: 'barcelona',
    league: 'PD',
    name: 'Barcelona',
    aliases: ['FC Barcelona'],
    attack_rating: 1.50,
    defense_rating: 0.78,
    form: 'WWWWW',
    crest_url: 'https://crests.football-data.org/81.png',
  },
  'atletico-madrid': {
    id: 'atletico-madrid',
    league: 'PD',
    name: 'Atletico Madrid',
    aliases: ['Club Atletico de Madrid'],
    attack_rating: 1.22,
    defense_rating: 0.68,
    form: 'WDWDW',
    crest_url: 'https://crests.football-data.org/78.png',
  },
  'athletic-bilbao': {
    id: 'athletic-bilbao',
    league: 'PD',
    name: 'Athletic Bilbao',
    aliases: ['Athletic Club'],
    attack_rating: 1.12,
    defense_rating: 0.85,
    form: 'WLDWW',
    crest_url: 'https://crests.football-data.org/77.png',
  },
  'villarreal': {
    id: 'villarreal',
    league: 'PD',
    name: 'Villarreal',
    aliases: ['Villarreal CF'],
    attack_rating: 1.25,
    defense_rating: 1.15,
    form: 'WWLDW',
    crest_url: 'https://crests.football-data.org/94.png',
  },
  'sevilla': {
    id: 'sevilla',
    league: 'PD',
    name: 'Sevilla',
    aliases: ['Sevilla FC'],
    attack_rating: 0.95,
    defense_rating: 1.08,
    form: 'LLDWL',
    crest_url: 'https://crests.football-data.org/559.png',
  },

  // Serie A
  'inter': {
    id: 'inter',
    league: 'SA',
    name: 'Inter Milan',
    aliases: ['Internazionale', 'Inter'],
    attack_rating: 1.42,
    defense_rating: 0.60,
    form: 'WWDWW',
    crest_url: 'https://crests.football-data.org/108.png',
  },
  'juventus': {
    id: 'juventus',
    league: 'SA',
    name: 'Juventus',
    aliases: ['Juventus FC'],
    attack_rating: 1.10,
    defense_rating: 0.52,
    form: 'DDWWD',
    crest_url: 'https://crests.football-data.org/109.png',
  },
  'ac-milan': {
    id: 'ac-milan',
    league: 'SA',
    name: 'AC Milan',
    aliases: ['Milan'],
    attack_rating: 1.28,
    defense_rating: 0.95,
    form: 'LWWLD',
    crest_url: 'https://crests.football-data.org/98.png',
  },
  'napoli': {
    id: 'napoli',
    league: 'SA',
    name: 'Napoli',
    aliases: ['SSC Napoli'],
    attack_rating: 1.26,
    defense_rating: 0.75,
    form: 'WWWDW',
    crest_url: 'https://crests.football-data.org/113.png',
  },
  'atalanta': {
    id: 'atalanta',
    league: 'SA',
    name: 'Atalanta',
    aliases: ['Atalanta BC'],
    attack_rating: 1.34,
    defense_rating: 1.02,
    form: 'WLWWL',
    crest_url: 'https://crests.football-data.org/102.png',
  },
  'roma': {
    id: 'roma',
    league: 'SA',
    name: 'AS Roma',
    aliases: ['Roma'],
    attack_rating: 1.14,
    defense_rating: 0.90,
    form: 'DDWDL',
    crest_url: 'https://crests.football-data.org/100.png',
  },

  // Bundesliga
  'bayern-munich': {
    id: 'bayern-munich',
    league: 'BL1',
    name: 'Bayern Munich',
    aliases: ['FC Bayern München'],
    attack_rating: 1.60,
    defense_rating: 0.72,
    form: 'WWWWW',
    crest_url: 'https://crests.football-data.org/5.png',
  },
  'leverkusen': {
    id: 'leverkusen',
    league: 'BL1',
    name: 'Bayer Leverkusen',
    aliases: ['Bayer 04 Leverkusen'],
    attack_rating: 1.48,
    defense_rating: 0.80,
    form: 'WDWWW',
    crest_url: 'https://crests.football-data.org/3.png',
  },
  'dortmund': {
    id: 'dortmund',
    league: 'BL1',
    name: 'Borussia Dortmund',
    aliases: ['Dortmund', 'BVB'],
    attack_rating: 1.35,
    defense_rating: 0.98,
    form: 'WLWDW',
    crest_url: 'https://crests.football-data.org/4.png',
  },
  'rb-leipzig': {
    id: 'rb-leipzig',
    league: 'BL1',
    name: 'RB Leipzig',
    aliases: ['Leipzig'],
    attack_rating: 1.28,
    defense_rating: 0.76,
    form: 'DWWDW',
    crest_url: 'https://crests.football-data.org/721.png',
  },
  'stuttgart': {
    id: 'stuttgart',
    league: 'BL1',
    name: 'VfB Stuttgart',
    aliases: ['Stuttgart'],
    attack_rating: 1.32,
    defense_rating: 1.05,
    form: 'WWLDW',
    crest_url: 'https://crests.football-data.org/10.png',
  },
  'eintracht-frankfurt': {
    id: 'eintracht-frankfurt',
    league: 'BL1',
    name: 'Eintracht Frankfurt',
    aliases: ['Frankfurt'],
    attack_rating: 1.24,
    defense_rating: 1.00,
    form: 'DWWLW',
    crest_url: 'https://crests.football-data.org/19.png',
  },

  // Ligue 1
  'psg': {
    id: 'psg',
    league: 'FL1',
    name: 'Paris Saint-Germain',
    aliases: ['PSG', 'Paris Saint-Germain FC'],
    attack_rating: 1.55,
    defense_rating: 0.68,
    form: 'WWWDW',
    crest_url: 'https://crests.football-data.org/524.png',
  },
  'marseille': {
    id: 'marseille',
    league: 'FL1',
    name: 'Olympique de Marseille',
    aliases: ['Marseille', 'OM'],
    attack_rating: 1.30,
    defense_rating: 0.85,
    form: 'WWLWW',
    crest_url: 'https://crests.football-data.org/516.png',
  },
  'monaco': {
    id: 'monaco',
    league: 'FL1',
    name: 'AS Monaco',
    aliases: ['Monaco'],
    attack_rating: 1.32,
    defense_rating: 0.80,
    form: 'WDWWW',
    crest_url: 'https://crests.football-data.org/548.png',
  },
  'lille': {
    id: 'lille',
    league: 'FL1',
    name: 'LOSC Lille',
    aliases: ['Lille'],
    attack_rating: 1.15,
    defense_rating: 0.78,
    form: 'WDLLW',
    crest_url: 'https://crests.football-data.org/521.png',
  },
  'lyon': {
    id: 'lyon',
    league: 'FL1',
    name: 'Olympique Lyonnais',
    aliases: ['Lyon'],
    attack_rating: 1.18,
    defense_rating: 1.12,
    form: 'LWWDL',
    crest_url: 'https://crests.football-data.org/523.png',
  },
  'lens': {
    id: 'lens',
    league: 'FL1',
    name: 'RC Lens',
    aliases: ['Lens'],
    attack_rating: 1.05,
    defense_rating: 0.65,
    form: 'DDWDD',
    crest_url: 'https://crests.football-data.org/546.png',
  }
};

export const MOCK_FIXTURES: Fixture[] = [
  // Premier League
  {
    id: 'pl-ars-che',
    league: 'PL',
    home_team_id: 'arsenal',
    away_team_id: 'chelsea',
    match_time: '2026-09-20T16:30:00Z',
    status: 'SCHEDULED',
    homeTeam: MOCK_TEAMS['arsenal'],
    awayTeam: MOCK_TEAMS['chelsea'],
    marketOdds: {
      fixture_id: 'pl-ars-che',
      bookmaker: 'Bet365 / Pinnacle Consensus',
      home_odds: 1.68,
      draw_odds: 3.90,
      away_odds: 5.25,
      over_25_odds: 1.82,
      under_25_odds: 2.05,
    }
  },
  {
    id: 'pl-mci-ast',
    league: 'PL',
    home_team_id: 'manchester-city',
    away_team_id: 'aston-villa',
    match_time: '2026-09-20T19:00:00Z',
    status: 'SCHEDULED',
    homeTeam: MOCK_TEAMS['manchester-city'],
    awayTeam: MOCK_TEAMS['aston-villa'],
    marketOdds: {
      fixture_id: 'pl-mci-ast',
      bookmaker: 'Bet365 / Pinnacle Consensus',
      home_odds: 1.45,
      draw_odds: 4.80,
      away_odds: 7.00,
      over_25_odds: 1.55,
      under_25_odds: 2.45,
    }
  },
  {
    id: 'pl-liv-wol',
    league: 'PL',
    home_team_id: 'liverpool',
    away_team_id: 'wolves',
    match_time: '2026-09-21T14:00:00Z',
    status: 'SCHEDULED',
    homeTeam: MOCK_TEAMS['liverpool'],
    awayTeam: MOCK_TEAMS['wolves'],
    marketOdds: {
      fixture_id: 'pl-liv-wol',
      bookmaker: 'Bet365 / Pinnacle Consensus',
      home_odds: 1.30,
      draw_odds: 5.75,
      away_odds: 9.50,
      over_25_odds: 1.44,
      under_25_odds: 2.80,
    }
  },
  {
    id: 'pl-tot-new',
    league: 'PL',
    home_team_id: 'tottenham',
    away_team_id: 'newcastle',
    match_time: '2026-09-21T16:30:00Z',
    status: 'SCHEDULED',
    homeTeam: MOCK_TEAMS['tottenham'],
    awayTeam: MOCK_TEAMS['newcastle'],
    marketOdds: {
      fixture_id: 'pl-tot-new',
      bookmaker: 'Bet365 / Pinnacle Consensus',
      home_odds: 2.25,
      draw_odds: 3.60,
      away_odds: 3.10,
      over_25_odds: 1.60,
      under_25_odds: 2.35,
    }
  },

  // La Liga
  {
    id: 'pd-rma-vil',
    league: 'PD',
    home_team_id: 'real-madrid',
    away_team_id: 'villarreal',
    match_time: '2026-09-20T19:00:00Z',
    status: 'SCHEDULED',
    homeTeam: MOCK_TEAMS['real-madrid'],
    awayTeam: MOCK_TEAMS['villarreal'],
    marketOdds: {
      fixture_id: 'pd-rma-vil',
      bookmaker: 'Pinnacle Consensus',
      home_odds: 1.42,
      draw_odds: 4.75,
      away_odds: 7.20,
      over_25_odds: 1.50,
      under_25_odds: 2.60,
    }
  },
  {
    id: 'pd-bar-ath',
    league: 'PD',
    home_team_id: 'barcelona',
    away_team_id: 'athletic-bilbao',
    match_time: '2026-09-21T18:00:00Z',
    status: 'SCHEDULED',
    homeTeam: MOCK_TEAMS['barcelona'],
    awayTeam: MOCK_TEAMS['athletic-bilbao'],
    marketOdds: {
      fixture_id: 'pd-bar-ath',
      bookmaker: 'Pinnacle Consensus',
      home_odds: 1.55,
      draw_odds: 4.20,
      away_odds: 6.00,
      over_25_odds: 1.65,
      under_25_odds: 2.25,
    }
  },
  {
    id: 'pd-atm-sev',
    league: 'PD',
    home_team_id: 'atletico-madrid',
    away_team_id: 'sevilla',
    match_time: '2026-09-21T20:00:00Z',
    status: 'SCHEDULED',
    homeTeam: MOCK_TEAMS['atletico-madrid'],
    awayTeam: MOCK_TEAMS['sevilla'],
    marketOdds: {
      fixture_id: 'pd-atm-sev',
      bookmaker: 'Pinnacle Consensus',
      home_odds: 1.52,
      draw_odds: 4.00,
      away_odds: 6.80,
      over_25_odds: 1.95,
      under_25_odds: 1.88,
    }
  },

  // Serie A
  {
    id: 'sa-int-mil',
    league: 'SA',
    home_team_id: 'inter',
    away_team_id: 'ac-milan',
    match_time: '2026-09-21T18:45:00Z',
    status: 'SCHEDULED',
    homeTeam: MOCK_TEAMS['inter'],
    awayTeam: MOCK_TEAMS['ac-milan'],
    marketOdds: {
      fixture_id: 'sa-int-mil',
      bookmaker: 'Pinnacle Consensus',
      home_odds: 1.78,
      draw_odds: 3.75,
      away_odds: 4.60,
      over_25_odds: 1.80,
      under_25_odds: 2.05,
    }
  },
  {
    id: 'sa-juv-nap',
    league: 'SA',
    home_team_id: 'juventus',
    away_team_id: 'napoli',
    match_time: '2026-09-20T16:00:00Z',
    status: 'SCHEDULED',
    homeTeam: MOCK_TEAMS['juventus'],
    awayTeam: MOCK_TEAMS['napoli'],
    marketOdds: {
      fixture_id: 'sa-juv-nap',
      bookmaker: 'Pinnacle Consensus',
      home_odds: 2.30,
      draw_odds: 3.15,
      away_odds: 3.35,
      over_25_odds: 2.20,
      under_25_odds: 1.68,
    }
  },
  {
    id: 'sa-rom-ata',
    league: 'SA',
    home_team_id: 'roma',
    away_team_id: 'atalanta',
    match_time: '2026-09-21T14:00:00Z',
    status: 'SCHEDULED',
    homeTeam: MOCK_TEAMS['roma'],
    awayTeam: MOCK_TEAMS['atalanta'],
    marketOdds: {
      fixture_id: 'sa-rom-ata',
      bookmaker: 'Pinnacle Consensus',
      home_odds: 2.50,
      draw_odds: 3.40,
      away_odds: 2.85,
      over_25_odds: 1.85,
      under_25_odds: 1.98,
    }
  },

  // Bundesliga
  {
    id: 'bl-bay-lev',
    league: 'BL1',
    home_team_id: 'bayern-munich',
    away_team_id: 'leverkusen',
    match_time: '2026-09-20T16:30:00Z',
    status: 'SCHEDULED',
    homeTeam: MOCK_TEAMS['bayern-munich'],
    awayTeam: MOCK_TEAMS['leverkusen'],
    marketOdds: {
      fixture_id: 'bl-bay-lev',
      bookmaker: 'Pinnacle Consensus',
      home_odds: 1.70,
      draw_odds: 4.40,
      away_odds: 4.20,
      over_25_odds: 1.38,
      under_25_odds: 3.10,
    }
  },
  {
    id: 'bl-dor-stu',
    league: 'BL1',
    home_team_id: 'dortmund',
    away_team_id: 'stuttgart',
    match_time: '2026-09-21T13:30:00Z',
    status: 'SCHEDULED',
    homeTeam: MOCK_TEAMS['dortmund'],
    awayTeam: MOCK_TEAMS['stuttgart'],
    marketOdds: {
      fixture_id: 'bl-dor-stu',
      bookmaker: 'Pinnacle Consensus',
      home_odds: 2.15,
      draw_odds: 3.90,
      away_odds: 3.10,
      over_25_odds: 1.50,
      under_25_odds: 2.60,
    }
  },
  {
    id: 'bl-lei-fra',
    league: 'BL1',
    home_team_id: 'rb-leipzig',
    away_team_id: 'eintracht-frankfurt',
    match_time: '2026-09-21T16:30:00Z',
    status: 'SCHEDULED',
    homeTeam: MOCK_TEAMS['rb-leipzig'],
    awayTeam: MOCK_TEAMS['eintracht-frankfurt'],
    marketOdds: {
      fixture_id: 'bl-lei-fra',
      bookmaker: 'Pinnacle Consensus',
      home_odds: 1.65,
      draw_odds: 4.10,
      away_odds: 5.00,
      over_25_odds: 1.62,
      under_25_odds: 2.30,
    }
  },

  // Ligue 1
  {
    id: 'fl-psg-ren',
    league: 'FL1',
    home_team_id: 'psg',
    away_team_id: 'lille',
    match_time: '2026-09-20T19:45:00Z',
    status: 'SCHEDULED',
    homeTeam: MOCK_TEAMS['psg'],
    awayTeam: MOCK_TEAMS['lille'],
    marketOdds: {
      fixture_id: 'fl-psg-ren',
      bookmaker: 'Pinnacle Consensus',
      home_odds: 1.48,
      draw_odds: 4.50,
      away_odds: 6.50,
      over_25_odds: 1.68,
      under_25_odds: 2.20,
    }
  },
  {
    id: 'fl-mar-lyo',
    league: 'FL1',
    home_team_id: 'marseille',
    away_team_id: 'lyon',
    match_time: '2026-09-21T18:45:00Z',
    status: 'SCHEDULED',
    homeTeam: MOCK_TEAMS['marseille'],
    awayTeam: MOCK_TEAMS['lyon'],
    marketOdds: {
      fixture_id: 'fl-mar-lyo',
      bookmaker: 'Pinnacle Consensus',
      home_odds: 1.85,
      draw_odds: 3.80,
      away_odds: 4.00,
      over_25_odds: 1.70,
      under_25_odds: 2.15,
    }
  },
  {
    id: 'fl-mon-len',
    league: 'FL1',
    home_team_id: 'monaco',
    away_team_id: 'lens',
    match_time: '2026-09-21T15:00:00Z',
    status: 'SCHEDULED',
    homeTeam: MOCK_TEAMS['monaco'],
    awayTeam: MOCK_TEAMS['lens'],
    marketOdds: {
      fixture_id: 'fl-mon-len',
      bookmaker: 'Pinnacle Consensus',
      home_odds: 1.95,
      draw_odds: 3.65,
      away_odds: 3.85,
      over_25_odds: 1.82,
      under_25_odds: 2.00,
    }
  }
];

export const MOCK_HISTORICAL_PARLAYS: AIParlay[] = [
  {
    id: 'hist-1',
    category: 'safe',
    title: 'Safe Combo #48',
    description: 'High-confidence home anchors across PL & La Liga with minimal variance.',
    legs: [
      {
        fixtureId: 'pl-liv-wol',
        league: 'PL',
        homeTeam: 'Liverpool',
        awayTeam: 'Wolves',
        market: '1X2',
        selection: '1',
        odds: 1.30,
        trueProb: 0.81,
        ev: 5.3,
        matchTime: '2026-09-21T14:00:00Z'
      },
      {
        fixtureId: 'pd-rma-vil',
        league: 'PD',
        homeTeam: 'Real Madrid',
        awayTeam: 'Villarreal',
        market: '1X2',
        selection: '1',
        odds: 1.42,
        trueProb: 0.74,
        ev: 5.1,
        matchTime: '2026-09-20T19:00:00Z'
      },
      {
        fixtureId: 'bl-bay-lev',
        league: 'BL1',
        homeTeam: 'Bayern Munich',
        awayTeam: 'Bayer Leverkusen',
        market: 'Totals',
        selection: 'Over 2.5',
        odds: 1.38,
        trueProb: 0.78,
        ev: 7.6,
        matchTime: '2026-09-20T16:30:00Z'
      }
    ],
    total_odds: 2.55,
    true_probability: 0.467,
    expected_value: 19.1,
    status: 'won',
    created_at: '2026-09-14T10:00:00Z'
  },
  {
    id: 'hist-2',
    category: 'value',
    title: 'Value Seeker #29',
    description: 'Mathematically positive expected value legs with edge against market lines.',
    legs: [
      {
        fixtureId: 'sa-int-mil',
        league: 'SA',
        homeTeam: 'Inter Milan',
        awayTeam: 'AC Milan',
        market: '1X2',
        selection: '1',
        odds: 1.78,
        trueProb: 0.62,
        ev: 10.4,
        matchTime: '2026-09-21T18:45:00Z'
      },
      {
        fixtureId: 'fl-mar-lyo',
        league: 'FL1',
        homeTeam: 'Olympique de Marseille',
        awayTeam: 'Olympique Lyonnais',
        market: '1X2',
        selection: '1',
        odds: 1.85,
        trueProb: 0.58,
        ev: 7.3,
        matchTime: '2026-09-21T18:45:00Z'
      },
      {
        fixtureId: 'pl-tot-new',
        league: 'PL',
        homeTeam: 'Tottenham Hotspur',
        awayTeam: 'Newcastle United',
        market: 'Totals',
        selection: 'Over 2.5',
        odds: 1.60,
        trueProb: 0.68,
        ev: 8.8,
        matchTime: '2026-09-21T16:30:00Z'
      }
    ],
    total_odds: 5.27,
    true_probability: 0.244,
    expected_value: 28.6,
    status: 'won',
    created_at: '2026-09-15T12:30:00Z'
  },
  {
    id: 'hist-3',
    category: 'safe',
    title: 'Safe Combo #49',
    description: 'Targeting favorites with strong expected goal margins.',
    legs: [
      {
        fixtureId: 'pd-bar-ath',
        league: 'PD',
        homeTeam: 'Barcelona',
        awayTeam: 'Athletic Bilbao',
        market: '1X2',
        selection: '1',
        odds: 1.55,
        trueProb: 0.68,
        ev: 5.4,
        matchTime: '2026-09-21T18:00:00Z'
      },
      {
        fixtureId: 'pl-mci-ast',
        league: 'PL',
        homeTeam: 'Manchester City',
        awayTeam: 'Aston Villa',
        market: '1X2',
        selection: '1',
        odds: 1.45,
        trueProb: 0.72,
        ev: 4.4,
        matchTime: '2026-09-20T19:00:00Z'
      }
    ],
    total_odds: 2.25,
    true_probability: 0.49,
    expected_value: 10.2,
    status: 'lost',
    created_at: '2026-09-16T09:15:00Z'
  },
  {
    id: 'hist-4',
    category: 'lotto',
    title: 'Weekend Lotto Moonshot #14',
    description: 'High-risk, high-payout accumulator across all Top 5 European leagues.',
    legs: [
      {
        fixtureId: 'pl-ars-che',
        league: 'PL',
        homeTeam: 'Arsenal',
        awayTeam: 'Chelsea',
        market: '1X2',
        selection: '1',
        odds: 1.68,
        trueProb: 0.64,
        ev: 7.5,
        matchTime: '2026-09-20T16:30:00Z'
      },
      {
        fixtureId: 'pd-atm-sev',
        league: 'PD',
        homeTeam: 'Atletico Madrid',
        awayTeam: 'Sevilla',
        market: '1X2',
        selection: '1',
        odds: 1.52,
        trueProb: 0.70,
        ev: 6.4,
        matchTime: '2026-09-21T20:00:00Z'
      },
      {
        fixtureId: 'bl-lei-fra',
        league: 'BL1',
        homeTeam: 'RB Leipzig',
        awayTeam: 'Eintracht Frankfurt',
        market: 'Totals',
        selection: 'Over 2.5',
        odds: 1.62,
        trueProb: 0.66,
        ev: 6.9,
        matchTime: '2026-09-21T16:30:00Z'
      },
      {
        fixtureId: 'fl-psg-ren',
        league: 'FL1',
        homeTeam: 'Paris Saint-Germain',
        awayTeam: 'LOSC Lille',
        market: '1X2',
        selection: '1',
        odds: 1.48,
        trueProb: 0.72,
        ev: 6.6,
        matchTime: '2026-09-20T19:45:00Z'
      },
      {
        fixtureId: 'sa-rom-ata',
        league: 'SA',
        homeTeam: 'AS Roma',
        awayTeam: 'Atalanta',
        market: 'Totals',
        selection: 'Over 2.5',
        odds: 1.85,
        trueProb: 0.58,
        ev: 7.3,
        matchTime: '2026-09-21T14:00:00Z'
      }
    ],
    total_odds: 11.31,
    true_probability: 0.124,
    expected_value: 40.2,
    status: 'pending',
    created_at: '2026-09-17T18:00:00Z'
  }
];
